### ISSUE TITLE
How to render changes?

### ISSUE THREAD

**Issue by bitbacchus** [r-spatialecology/gwdg_hpc_guide#10]
I fixed some typos, but when I hit the *knit* button in RStudio, all the *.css stuff gets deleted.

**Comment by marcosci** [comment]
did rmarkdown::render() work? I think knit != render ... somehow 🤷

**Comment by bitbacchus** [comment]
no, this does the same on my machine. It seems to render the index.html just fine but deletes the index_files folder for some reason.

**Comment by marcosci** [comment]
Just assuming, based on my knowledge of sitting next to for a couple of years ... it s a weird tool you use to block something? :D 

I just pushed the knitted version ... looks fine on my machine? :) Maybe ... I don't know, an update is missung or something like that?

**Comment by bitbacchus** [comment]
Thx, @marcosci !
