### ISSUE TITLE
Link to our documentation

### ISSUE THREAD

**Issue by marcusboden** [r-spatialecology/gwdg_hpc_guide#11]
Hi,

could you update this guide regarding ssh-key upload? Or at least add some prominent links to our official [Connect with ssh page](https://info.gwdg.de/docs/doku.php?id=en:services:application_services:high_performance_computing:connect_with_ssh)?

Best,
Marcus

**Comment by mhesselbarth** [comment]
Should be fixed: f6e42dcbc8999be277bf10fa4019df3c5530ea63

Please let me know if it's ok.

**Comment by marcusboden** [comment]
That's fine, thanks! One more thing: The alias reference medium-fat,medium-fmz, which are no longer available.

**Comment by mhesselbarth** [comment]
Okay, I will have a look and update them as well. Thanks for the input. 

I will close this issue once the aliases are fixed. Please feel free to re-open or open a new one if needed.

**Comment by mhesselbarth** [comment]
50391f5
