### ISSUE TITLE
ssh_exchange_identifcation: Connection closed by remote host

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/gwdg_hpc_guide#8]
Not sure why this is happening from time to time on the server...after waiting for about a day always works again.

**Comment by marcosci** [comment]
I got the same error using my google cloud from time to time, what fixed it was changing the ssh command to:

```bash
ssh -v -c aes256-ctr user@hpc
```

... for clustermq I think you can do that in `~/.ssh/config` ... if that fixes your problem, we could include it in the guide.

**Comment by mhesselbarth** [comment]
I will try later...however, not sure how to test and reproduce the error because I have no idea why and when it is actually occurring

**Comment by mhesselbarth** [comment]
Not sure if related, sometimes also I get 

```
connect_to localhost port 6256: failed.
connect_to localhost port 6256: failed.
connect_to localhost port 6256: failed.
```
